"""initial schema

Revision ID: 11c110229789
Revises: 
Create Date: 2026-09-29 04:58:12.581336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c110229789'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('normalized_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalized_name', name='uq_tags_kind_normalized_name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_kind'), 'tags', ['kind'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('abilities', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('origin_anime', sa.String(length=255), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_data', sa.LargeBinary(), nullable=True),
    sa.Column('avatar_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_character_name'), 'characters', ['character_name'], unique=False)
    op.create_index(op.f('ix_characters_created_by'), 'characters', ['created_by'], unique=False)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('character_ability_stats',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('magic', sa.Integer(), nullable=False),
    sa.Column('technique', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('character_images',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('secure_url', sa.String(length=1000), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_character_id', sa.Integer(), nullable=False),
    sa.Column('target_character_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_character_id', 'target_character_id', name='uq_character_relationship_pair')
    )
    op.create_index(op.f('ix_character_relationships_id'), 'character_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_character_relationships_source_character_id'), 'character_relationships', ['source_character_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_target_character_id'), 'character_relationships', ['target_character_id'], unique=False)
    op.create_table('character_tags',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'tag_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('character_tags')
    op.drop_index(op.f('ix_character_relationships_target_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_source_character_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_table('character_images')
    op.drop_table('character_ability_stats')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_created_by'), table_name='characters')
    op.drop_index(op.f('ix_characters_character_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_kind'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
